FROM python:3.10.9-slim-bullseye

SHELL ["/bin/bash", "-c"]

RUN pip3 install --no-cache-dir -r https://raw.githubusercontent.com/SWIFT-HEP/analysis-grand-challenge/main/analyses/cms-open-data-ttbar/requirements.txt
